config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :messages
  devise_for :users

  get 'home/about'
  root "home#index"

  get '*', to: 'errors#not_found', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'cancel_form' , to: 'application#cancel_form'
  get 'cancel_modal' , to: 'application#cancel_modal'
  
  resources :conversations do    
    member do
      get 'modal'
      get 'search_users'
    end
  end

end

app/models/task.rb
# app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  # Define the possible statuses as a constant
  STATUSES = ["pending", "completed"]

  # Validation example (you can adjust as needed)
  validates :title, presence: true
  validates :status, inclusion: { in: STATUSES }

  after_create_commit :create_notification_for_insert
  after_update_commit :create_notification_for_update
  after_destroy_commit :create_notification_for_delete

  private

  def create_notification_for_insert
    description = "Added task: #{title}"
    Notification.create(user: user, notifiable: self, read: false, action: "Added", description: description)
  end

  def create_notification_for_update
    description = "Updated task: #{title}"
    Notification.create(user: user, notifiable: self, read: false, action: "Updated", description: description)
  end
  
  def create_notification_for_delete
    description = "Deleted task: #{title}"
    Notification.create(user: user, notifiable: self, read: false, action: "deleted", description: description)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  # GET /tasks or /tasks.json
  def index
    #@tasks = Task.all
    column = params[:column] || 'title'

    if params[:filter].present?
      search_query = "%#{params[:filter].downcase}%"
      filtered = Task.where("LOWER(tasks.title) LIKE ? and user_id = ?", search_query, current_user.id)      
    elsif params[:status].present?
      filtered = Task.where("LOWER(tasks.status) = ? and user_id = ?", params[:status], current_user.id)
    else
     filtered =  Task.where("tasks.user_id = ?", current_user.id)
    end
  
    filtered = filtered.order(column)    
    @pagy, @tasks = pagy(filtered,items:9)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
   #@task = Task.new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    #@task = Task.new(task_params)
     @task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user    
    @user = current_user.tasks.find_by(id: params[:id ])
    redirect_to tasks_path, notice: "Not Authorized to edit this Task" if @user.nil?    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :dueDate, :status, :user_id, images: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, html: { class: "max-w-md mx-auto bg-white border-l-8 border-blue-500 p-6 mb-4 rounded-md shadow-md" }) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
      <h2 class="font-semibold"> <%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul class="mt-2">
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :title, class: "text-center bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200", maxlength: 20 %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_area :description, class: "text-center bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200", maxlength: 100 %>
  </div>

  <div class="mb-4">
    <%= form.label :dueDate, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.datetime_select :dueDate, class: "bg-gray-200 p-2 w-full border border-blue rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" %>
  </div>

  <div class="mb-4">
    <%= form.label :status, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.select :status, ['pending', 'completed'], {}, class: "text-center bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200" %>
  </div>

  <div class="mb-4">   
    <%= form.number_field :user_id, id: :task_user_id,
     class: "text-center bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200",
     value: current_user.id, type: :hidden
     %>
  </div>

  <%= form.label :images %>
  <%= form.file_field :images, multiple: true, direct_upload: true %>

  <div class="flex items-center justify-center">
    <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="max-w-md mx-auto">
  <h1 class="text-3xl font-semibold">Editing Task</h1>

  <div class=" rounded px-8  pt-6 pb-8 mb-4">
    <%= render 'form', task: @task %>
  </div>

  <div class="flex justify-between">
    <%= link_to 'Show', @task, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    <%= link_to 'Back', tasks_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="max-w-3xl mx-auto px-4 mt-2">
  <div class="flex items-center justify-between pb-6 border-b dark:border-slate-700">
    <h1 class="font-bold text-3xl">My Tasks</h1>
    <div class="flex items-center justify-end">
      <%= form_with url: tasks_path, method: :get, data: { turbo_frame: "tasks", turbo_action: "advance", controller: 'form', action: "input->form#submit" } do %>
        <%= text_field_tag "filter", nil, placeholder: "Filter (title)", class: "inline-block rounded-md border border-gray-200 outline-none px-3 py-2 w-full" %>
      <% end %>
    </div>
  </div>

  <%= turbo_frame_tag "tasks_data" do %>
  <div class="flex flex-wrap justify-center">
  <!-- Filter Links -->
  <div class="text-center mb-6 md:mb-0 mr-10">
    <h2 class="text-lg font-bold mb-2">Sort:</h2>
    <div class="flex items-center space-x-4">
      <%= link_to "Title", tasks_path(column: "title"), class: "text-gray-700 rounded-full p-2 bg-transparent shadow-md hover:bg-gray-200 transition duration-300 ease-in-out" %>
      <%= link_to "Description", tasks_path(column: "description"), class: "text-gray-700 rounded-full p-2 bg-transparent shadow-md hover:bg-gray-200 transition duration-300 ease-in-out" %>
      <%= link_to "Status", tasks_path(column: "status"), class: "text-gray-700 rounded-full p-2 bg-transparent shadow-md hover:bg-gray-200 transition duration-300 ease-in-out" %>
    </div>
  </div>

  <!-- Sort Links -->
  <div class="text-center">
    <h2 class="text-lg font-bold mb-2">Filter:</h2>
    <div class="flex items-center space-x-4">
      <%= link_to "Completed", tasks_path(status: "completed"), class: " text-gray-700 rounded-full p-2 bg-transparent shadow-md hover:bg-gray-200 transition duration-300 ease-in-out" %>
      <%= link_to "Pending", tasks_path(status: "pending"), class: "text-gray-700 rounded-full p-2 bg-transparent shadow-md hover:bg-gray-200 transition duration-300 ease-in-out" %>
      <%= link_to "Reset filter", tasks_path, class: "text-gray-700 rounded-full p-2 bg-transparent shadow-md hover:bg-gray-200 transition duration-300 ease-in-out" %>
    </div>
  </div>
</div>




<%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      <%= turbo_frame_tag "tasks_data" do %>
   
   <div class="max-w-full overflow-x-auto flex flex-wrap justify-center">
      <% @tasks.each do |task| %>
        <% if task.user_id == current_user.id %>
          <div class="bg-white text-wrap border-l-8 <%= task.status == "pending" ? 'border-blue-500' : 'border-green-500' %> text-black px-6 py-4 rounded-lg shadow-md m-4 max-w-sm">
            <p style="overflow-wrap: break-word;" class="font-bold text-lg mb-2">
              <%= task.title %>
              <span class="inline-block text-white text-xs font-bold capitalize px-2 py-1 rounded-full ml-2 <%= task.status == "pending" ? 'bg-blue-500' : 'bg-green-500' %>">
                <%= task.status %>
              </span>
            </p>
            <p class="text-gray-700 mb-2" style="overflow-wrap: break-word;"><%= task.description %></p> <!-- Apply overflow-wrap here -->
           <p class="text-gray-600"><strong>Due Date:</strong> <%= task.dueDate.strftime('%B %d, %Y %I:%M %p') %></p>


             <div class="flex justify-end mt-4">
                <%= link_to task, data: { turbo_frame: "_top" }, class: "font-bold text-gray-400 hover:text-white hover:bg-blue-500 border border-gray-400 rounded-full px-4 py-2 transition duration-300 ease-in-out" do %>
                  <i class="fas fa-eye"></i>
                <% end %>

                <%= link_to edit_task_path(task), data: { turbo_frame: "_top" }, class: "font-bold text-gray-400 hover:text-white hover:bg-green-500 border border-gray-400 rounded-full px-4 py-2 ml-2 transition duration-300 ease-in-out" do %>
                  <i class="fas fa-edit"></i>
                <% end %>

                <%= button_to task, method: :delete, remote: true, data: { turbo_frame: "_top", turbo_confirm: 'Are you sure?' }, class: "font-bold bg-transparent text-gray-400 hover:text-white hover:bg-red-500 border border-gray-400 rounded-full px-4 py-2 ml-2 transition duration-300 ease-in-out" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>

          </div>
        <% end %>
      <% end %>
      
    </div>
  <% end %>
  
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="max-w-md mx-auto mt-1 px-4">
  <h1 class=" text-3xl font-bold mb-4">New Task</h1>

  <%= render 'form', task: @task, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" %>

  <%= link_to 'Back', tasks_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
</div>

app/views/tasks/show.html.erb
<div class="mt-2 max-w-4xl mx-auto">
  <div class="bg-white rounded-lg overflow-hidden shadow-md">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <!-- Left Column -->
      <div class="border-blue-500 border-l-8 p-6">
        <div class="shadow-md pb-2">
          <h1 class="text-3xl text-center p-3 font-bold">
            <%= @task.title %>
            <span class="text-center inline-block bg-blue-500 text-white text-xs font-bold capitalize px-2 py-1 rounded-full ml-2">
              <%= @task.status %>
            </span>
          </h1>
        </div>
        <div class="mb-6">
          <p class="text-lg text-center font-semibold">
            <!-- Add any additional content here if needed -->
          </p>
        </div>
        <div class="mb-6">
          <p class="text-lg text-center" style="overflow-wrap: break-word;">
            <strong>Description:</strong> <%= @task.description %>
          </p>
        </div>
        <div class="mb-6">
          <p class="text-lg text-center font-semibold">
            <strong>Due Date:</strong> <%= @task.dueDate.strftime('%Y-%m-%d') %>
          </p>
        </div>
        <div class="mt-2 flex items-center justify-between">
          <%= link_to 'Edit', edit_task_path(@task), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded focus:outline-none focus:shadow-outline transition duration-300 ease-in-out" %>
          <%= link_to 'Back', tasks_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      </div>

      <!-- Right Column -->
      <div class="p-6 h-96 overflow-y-auto">
        <% if @task.images.attached? %>
          <div class="grid grid-cols-1 gap-4">
            <% @task.images.each do |image| %>
              <div class="w-full h-auto">
                <%= image_tag image, class: "object-cover w-full h-full rounded-lg shadow-md" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>