config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :messages
  devise_for :users

  get 'home/about'
  root "home#index"

  get '*', to: 'errors#not_found', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'cancel_form' , to: 'application#cancel_form'
  get 'cancel_modal' , to: 'application#cancel_modal'
  
  resources :conversations do    
    member do
      get 'modal'
      get 'search_users'
    end
  end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages
    has_many :users, through: :conversation_users    
    has_one_attached :cover_art


    private
   
    def excluding_user
     conversation_id = ConversationUser.where(user_id:  current_user.id ).first.id
     @messages = Message.where(conversation_id: conversation_id)

    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  before_action :authenticate_user!
  
  def modal         
    set_conversations

    @conversation = Conversation.new

    render turbo_stream: turbo_stream.update(
      "modal_#{current_user.id}",
      partial: 'conversations/modal',
      locals: { conversations: @conversations , conversation: @conversation }
    )
    
  end
  

  def show
    Rails.logger.debug("PARAMS:: #{params.inspect}")

    set_conversations
    
    if params[:id]      

          begin
          @conversation = Conversation.find(params[:id])
          rescue ActiveRecord::RecordNotFound => e
            @conv_user = ConversationUser.find(params[:id])        
            @conversation = Conversation.find(@conv_user.conversation_id)
          end
        
        if @conversation
          
          @messages = @conversation.messages
          @receivers_id = ConversationUser.where(conversation_id: @conversation.id).pluck(:user_id)
          @receivers = User.where(id: @receivers_id).where.not(id: current_user.id)
           
          render turbo_stream: 
          turbo_stream.replace(
            "modal_#{current_user.id}",
            partial: 'conversations/modal',
            locals: { conversations: @conversations , conversation: @conversation , messages: @messages , receivers: @receivers }
          )

        end

      end


  end

  
  def new
    @conversation = ConversationUser.new
    @users = User.where.not(id: current_user.id)
    render turbo_stream: turbo_stream.update(
      "new_conversation_#{current_user.id}",
      partial: 'conversations/new',
      locals: { conversation: @conversation , users: @users }
    )
  end

  def create

    

    Rails.logger.debug "Params: #{params.inspect}"
    
    # Create a new conversation
    @conv = Conversation.create
    @conversation = @conv
    # Create ConversationUser records for the new conversations
    ConversationUser.create(conversation_id: @conv.id, user_id: params[:conversation][:user_id])
    ConversationUser.create(conversation_id: @conv.id, user_id: current_user.id)

    # Create the message in the new conversation if content was sent via params
    if params[:conversation][:content].present?
      @conv.messages.create(content: params[:conversation][:content], user_id: current_user.id)
    end

    # Get all conversations where user is involved
    conversation_ids = current_user.conversation_users.pluck(:conversation_id)
    
    if conversation_ids.any?
      # Get all conversations where the user is involved
      conversations = ConversationUser.where(conversation_id: conversation_ids)
    else
      conversations = ConversationUser.none
    end

    Rails.logger.debug "Conv:::::: #{@conv.messages.inspect}"

   @messages = @conv.messages
   @receivers_id = ConversationUser.where(conversation_id: @conv.id).pluck(:user_id)
   @receivers = User.where(id: @receivers_id).where.not(id: current_user.id)
    # Get all conversations excluding the user
    @conversations = conversations.where.not(user_id: current_user.id)  
    
        render turbo_stream:[

          
          turbo_stream.update(
            "new_conversation_#{current_user.id}",
            ""
            ),
            
        turbo_stream.update(
          "modal_#{current_user.id}",
          partial: 'conversations/modal',
          locals: { conversations: @conversations , conversation: @conversation , messages: @messages , receivers: @receivers}
        )]     
  end

  def search_users
    @users = User.where("username ILIKE ?", "%#{params[:search]}%").limit(2)
    render turbo_stream:  turbo_stream.update(
      "user_select_frame_#{current_user.id}",
      partial: 'conversations/user_select',
      locals: { users: @users }
    )
  end 

  private

  def conversation_params
    params.require(:conversation).permit(:id , :content , :user_id, :conversation_id, :search)
  end

  def set_conversations
    # get all conversations where user is involved
    @conversations = Conversation.new
    conversation_ids = current_user.conversation_users.pluck(:conversation_id)
  
    if conversation_ids.any?
      # get all conversations where user is involved, but exluding him
      @conversations = ConversationUser.where(conversation_id: conversation_ids)
      @conversations = @conversations.where.not(user_id: current_user.id).select('DISTINCT ON (conversation_id) *').order('conversation_id, created_at DESC')      
    else
      @conversations = []
    end

  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_chat_messages.html.erb
<%= turbo_stream.replace "chat_messages" do %>
  <%= render partial: 'messages/message', collection: @conversation.messages %>
<% end %>

app/views/conversations/_conversations.html.erb
        <ul>
        <% @conversations.reverse_each do |conversation| %>
        <li class="mb-4">
            <%= link_to conversation_path(conversation), data: { turbo_frame: "modal" }, class: "flex items-center p-2 hover:bg-gray-200 rounded-lg" do %>
            <%= image_tag conversation.user.avatar, class: "w-12 h-12 rounded-full mr-3" if conversation.user.avatar.attached? %>
            <div>
                <p class="text-gray-900 font-semibold"><%= conversation.user.username %></p>
                <p class="text-gray-600 text-sm"><%= conversation.user.email %></p>
            </div>
            <% end %>
        </li>
        <% end %>
        </ul>

app/views/conversations/_messages.html.erb
<% @conversation.messages.each do |message| %>
  <div class="flex mb-4 <%= message.user == current_user ? 'justify-end' : 'justify-start' %>">
    <div class="<%= message.user == current_user ? 'bg-blue-500 text-white' : 'bg-gray-200 text-gray-900' %> rounded-lg p-4 max-w-md shadow-lg">
      <div class="flex items-center mb-2">
        <div class="text-sm font-semibold <%= message.user == current_user ? 'text-blue-200' : 'text-gray-700' %>"><%= message.user.username %></div>
      </div>
      <div class="text-base border-b border-gray-300 pb-2 mb-2"><%= message.content %></div>
      <div class="text-xs text-gray-400 mt-1 text-right"><%= time_ago_in_words(message.created_at) %> ago</div>
    </div>
  </div>
<% end %>

app/views/conversations/_modal.html.erb
<%= turbo_frame_tag "modal_#{current_user.id}", class: "z-50" do %>
  <div class="fixed inset-0 flex items-center justify-center z-40">
    <div class="absolute inset-0 bg-black opacity-50"></div>
    <div class="bg-white rounded-lg shadow-xl max-h-full w-4/5 md:w-1/2 lg:w-2/3 z-50 overflow-y-auto">
      <div class="flex justify-between items-center bg-sky-500 p-4 rounded-t-lg">
        <div class="text-white font-semibold w-full text-center">Chat</div>
        <%= link_to cancel_modal_path, data: { turbo_frame: "modal_#{current_user.id}" } do %>
          <i class="fas fa-times text-red"></i>
        <% end %>
      </div>

      <div class="flex h-screen">
        <!-- Left Column: Conversations List -->
        <!-- Turbo Frame for new conversation form -->
        <%= turbo_frame_tag "new_conversation_#{current_user.id}", class: "z-51" do %>        
        <% end %>

        <div class="w-full md:w-1/3 lg:w-1/4 bg-gray-100 border-r overflow-y-auto">
          <div class="p-4">
            <h2 class="text-xl font-bold mb-4">Conversations</h2>
            <%= link_to new_conversation_path, data: { turbo_frame: "new_conversation_#{current_user.id}" }, class: "text-white bg-blue-500 hover:bg-blue-600 p-2 rounded-full" do %>
              <i class="fas fa-plus"></i>
            <% end %>
            <%= turbo_frame_tag "conversations_#{current_user.id}", class: "z-51" do %>        
              <ul>

                <% @conversations.reverse_each do |conversation| %>
                  <li class="mb-4">
                    <%= link_to conversation_path(conversation), data: { turbo_frame: "modal_#{current_user.id}" }, class: "flex items-center p-2 hover:bg-gray-200 rounded-lg" do %>
                      <%= image_tag conversation.user.avatar, class: "w-12 h-12 rounded-full mr-3" if conversation.user.avatar.attached? %>
                      <div>
                        <p class="text-gray-900 font-semibold"><%= conversation.user.username %></p>
                        <p class="text-gray-600 text-sm"><%= conversation.user.email %></p>
                      </div>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>

        <!-- Right Column: Chat Messages and Form -->
        <div class="w-full md:w-2/3 lg:w-3/4 bg-white flex flex-col overflow-y-auto">
            
            
            <!-- Messages Receiver(s) details -->
              <% if @receivers %>             
                <div class="p-6 bg-white shadow-md rounded-lg">                  
                  <div class="flex flex-wrap space-x-4">
                    <% @receivers.first(4).each do |user| %>
                      <div class="relative group">
                        <%= image_tag(user.avatar, class: "w-16 h-16 rounded-full object-cover border-2 border-gray-300 hover:border-blue-500 transition duration-300") %>
                        <div class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-2/3 bg-black text-white text-xs rounded-lg px-2 py-1 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                          <%= user.username %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>


          <!-- Messages List -->
          <%= turbo_frame_tag "chat_messages_#{current_user.id}" do %>
              <div class="flex-1 px-4 p-4 overflow-y-auto bg-gray-100 rounded-lg shadow-inner">
                 <div id="chat_messages" class="space-y-4">
                  <%= render partial: 'conversations/messages' %>
                 </div>
              </div>     
          <% end %>
        
      </div>
      </div>

      <!-- New Message Form -->
            <% if @conversation.id %>
            <div class="p-4 border-t bg-gray-50 sticky bottom-0">
             <%= form_with model: Message.new , url: messages_path, local: false, data: { turbo_frame: "chat_messages_#{current_user.id}" }, id: "new_message_form" do |form| %>
              <div class="flex items-center">
                <%= form.text_area :content, class: "flex-1 border rounded-lg p-3 resize-none shadow-sm focus:ring-2 focus:ring-blue-500 focus:outline-none", rows: 1, placeholder: "Type a message..." %>

                <%= form.hidden_field :conversation_id, value: @conversation.id %>

                <%= form.submit "Send", class: "ml-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500" %>
              </div>
            <% end %>

            </div>
          <% end %>



    </div>
  </div>
<% end %>

app/views/conversations/_new.html.erb
<div class="fixed inset-0 flex items-center justify-center z-50">
  <div class="absolute inset-0 bg-black opacity-50"></div>
  <div class="bg-white rounded-lg shadow-xl max-h-full w-4/5 md:w-1/2 lg:w-1/3 z-50 overflow-y-auto p-6">
    <div class="flex justify-between items-center border-b pb-4 mb-4">
      <h1 class="text-2xl font-bold">New Conversation</h1>
      <%= link_to cancel_form_path, data: { turbo_frame: "new_conversation_#{current_user.id}" }, class: "text-gray-600 hover:text-gray-900" do %>
        <i class="fas fa-times text-lg"></i>
      <% end %>
    </div>

    <%= form_with model: Conversation.new, url: conversations_path, data: { turbo_frame: "conversations_#{current_user.id}" }, method: :post, local: true, class: "space-y-6" do |form| %>
      <div class="space-y-2">
        <%= form.label :user_id, "Select User", class: "block text-sm font-medium text-gray-700" %>
        <%= form.select :user_id, options_from_collection_for_select(@users, :id, :username), {}, class: "bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200 text-center" %>
      </div>

      <div class="space-y-2">
        <%= form.label :content, "Message (Optional)", class: "block text-sm font-medium text-gray-700" %>
        <%= form.text_field :content, placeholder: "Hi....", class: "bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200 text-center" %>
      </div>

      <div>
        <%= form.submit "Create Conversation", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/conversations/_user_select.html.erb
<%= form.select :user_id, options_from_collection_for_select(@users, :id, :username), {}, class: "bg-gray-200 p-2 w-full border border-transparent rounded-md shadow-sm focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-200 text-center", id: "user-select" %>

app/views/conversations/chat.html.erb
<%= turbo_stream.replace "chat_messages" do %>
  <%= render partial: 'messages/message', collection: @conversation.messages %>
<% end %>