config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :messages
  devise_for :users

  get 'home/about'
  root "home#index"

  get '*', to: 'errors#not_found', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'cancel_form' , to: 'application#cancel_form'
  get 'cancel_modal' , to: 'application#cancel_modal'
  
  resources :conversations do    
    member do
      get 'modal'
      get 'search_users'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, except: [:about]
    
    def index    
      @tasks = Task.where(user_id: current_user.id)
    end      
    
    def about
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class=" mt-2 py-4 lg:py-8  w-full">
<hr />
  <div class="mt-2 container mx-auto px-4">
    <div class="flex flex-col lg:flex-row justify-between items-center">
      <p class="font-bold mb-4 lg:mb-0 lg:mr-6">© 2024 Exito Travel To Do App</p>
      <ul class="flex">
        <li class="mr-6"><a href="#" class="font-bold hover:text-gray-500">Privacy Policy</a></li>
        <li><a href="#" class="font-bold hover:text-gray-500">Terms of Service</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="bg-black rounded">
  <div class="container mx-auto px-4 py-6">
    <div class="flex items-center justify-between">
      <!-- Brand Logo -->
      <a href="<%= root_path %>" class="text-white hover:text-blue-300 font-bold text-xl">Home</a>
           
      <!-- Mobile Menu Toggle Button -->
      <button id="mobile-menu-toggle" class="lg:hidden text-white focus:outline-none">
        <svg class="h-6 w-6 fill-current" viewBox="0 0 24 24">
          <path d="M4 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 5h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 5h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/>
        </svg>
      </button>

      <!-- Responsive Menu Items -->
      <div id="mobile-menu" class="hidden lg:flex lg:items-center lg:w-auto">
        <ul class="flex flex-col lg:flex-row list-none lg:ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to 'My To Dos', tasks_path, class: "text-white hover:text-blue-300 px-3 py-2 lg:px-4 lg:py-0" %></li>
            <li><%= link_to 'Create Task', new_task_path, class: "text-white hover:text-blue-300 px-3 py-2 lg:px-4 lg:py-0" %></li>            
            
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path, class: "text-white hover:text-blue-300 px-3 py-2 lg:px-4 lg:py-0" %></li>
            <li><%= link_to 'Sign In', new_user_session_path, class: "text-white hover:text-blue-300 hover:text-gray-900 px-3 py-2 lg:px-4 lg:py-0" %></li>
          <% end %>
          
          <li><%= link_to 'About', home_about_path, class: "text-white hover:text-blue-300 hover:text-gray-900 px-3 py-2 lg:px-4 lg:py-0" %></li>
                  
                  
          <% if !current_user.nil?%>
              
                    <li class="relative"> 
              <a href="javascript:;" class="block px-4 flex text-sm rounded-full focus:outline-none" id="notify_msg">
                <div class="relative inline-block">
                  <span class="material-symbols-outlined text-2xl text-white">
                    <i class="fas fa-envelope text-yellow-400"></i>
                  </span>
                      <%= turbo_stream_from "messages_unread_count_#{current_user.id}" %>
                  <span class="flex justify-center absolute text-blue-300 -top-2 ltr:-right-1 rtl:-left-1 text-center bg-rose-500 px-1 text-white rounded-full text-xs"
                        id="messages_unread_count">
                    <%= current_user.messages.unread.count %>
                  </span>
                </div>
              </a>
              <%= render 'messages/dropdown' %>
            </li>

            <li>
              <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
              <button href="javascript:;" id="notify_user" type="button" class="flex text-sm bg-light border-white rounded-full md:me-0 focus:ring-4 focus:ring-yellow-400 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
              <span class="sr-only">Open user menu</span>

                  <% if !current_user.nil? %>
                  <% if current_user.avatar.attached? %>
                   <div class="mb-5">
                   <%= image_tag(current_user.avatar, class: "w-8 h-8 rounded-full") %>
                   </div>
                   <% else %>
                   <img class="w-8 h-8 rounded-full" src="/docs/images/people/profile-picture-3.jpg" alt="user photo">
                   <% end %>
                   
                <% end %>

              </button>
              <!-- Dropdown menu -->
            <div class="relative hidden" id="user-dropdown">
          <div class="w-50 origin-top-right absolute right-0 rounded top-full z-20 py-0.5 text-left bg-white border shadow-md lg:block">
            <div class="p-3 font-normal border-b border-gray-200">
              <% if user_signed_in? %>
                <div class="relative">
                  <%= link_to :back do %>
                    <span class="block text-sm text-gray-500 truncate dark:text-gray-400"><%= current_user.email %></span>
                  <% end %>
                </div>
              <% end %>
            </div>
            <ul class="py-2" aria-labelledby="user-menu-button">
              <% if user_signed_in? %>
                <li class="border-b border-gray-200">
                  <%= link_to 'Edit Profile', edit_user_registration_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-100" %>
                </li>
                <li>
                  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: " block w-full text-left px-4 py-2 text-gray-700 hover:text-red-400 hover:bg-gray-100" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>

      

      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
  </div>
            </li>
                
           <li class="relative"> 
              <a href="javascript:;" class="block px-4 flex text-sm rounded-full focus:outline-none" id="notify">
                <div class="relative inline-block">
                  <span class="material-symbols-outlined text-2xl text-white">
                    <i class="fas fa-bell text-yellow-400"></i>
                  </span>
                  <%= turbo_stream_from current_user.notifications %>
                  <span class="flex justify-center absolute text-blue-300 -top-2 ltr:-right-1 rtl:-left-1 text-center bg-rose-500 px-1 text-white rounded-full text-xs"
                        id="notifications_unread_count">
                    <%= current_user.notifications.unread.count %>
                  </span>
                </div>
              </a>
              <%= render 'notifications/dropdown' %>
            </li>
                  <% end%>
        </ul>
      </div>
    </div>
  </div>
</nav>

<script>
  document.getElementById('mobile-menu-toggle').addEventListener('click', function() {
    var mobileMenu = document.getElementById('mobile-menu');
    mobileMenu.classList.toggle('hidden');
  });

  document.getElementById('notify').addEventListener('click', function() {
    var dropdown = document.getElementById('notifications-dropdown');
    var dropdown_msg = document.getElementById('messages_dropdown');
    var dropdown_usr = document.getElementById('user-dropdown');
    dropdown.classList.toggle('hidden');

    if(!dropdown_msg.classList.contains('hidden')){
      
      dropdown_msg.classList.toggle('hidden');
    }
    if(!dropdown_usr.classList.contains('hidden')){
      
      dropdown_usr.classList.toggle('hidden');
    }
  });

  document.getElementById('notify_msg').addEventListener('click', function() {
    var dropdown = document.getElementById('messages_dropdown');
    var dropdown_not = document.getElementById('notifications-dropdown');
    var dropdown_usr = document.getElementById('user-dropdown');
    

    dropdown.classList.toggle('hidden');

    if(!dropdown_not.classList.contains('hidden')){
      
      dropdown_not.classList.toggle('hidden');
    }
    
     if(!dropdown_usr.classList.contains('hidden')){
      
      dropdown_usr.classList.toggle('hidden');
    }

  });

  document.getElementById('notify_user').addEventListener('click', function() {
    var dropdown = document.getElementById('user-dropdown');
    var dropdown_not = document.getElementById('notifications-dropdown');
    var dropdown_msg = document.getElementById('messages_dropdown');    
    dropdown.classList.toggle('hidden');


    if(!dropdown_not.classList.contains('hidden')){
      
      dropdown_not.classList.toggle('hidden');
    }

    if(!dropdown_msg.classList.contains('hidden')){
      
      dropdown_msg.classList.toggle('hidden');
    }
    
  });
</script>

app/views/home/about.erb
<div class=" max-w-3xl mx-auto py-8 px-6 bg-gray-50 rounded-lg shadow-lg mt-2">
  
  <h1 class="text-4xl font-semibold mb-8 text-center">About Me</h1>

<div class="shadow-lg border-blue-400 border-l-8 rounded p-2 mb-2">

  <div class="mb-8">
    <p class="text-lg"><strong>Name:</strong> Fernando Jose Lagos Lovo</p>
  </div>

  <div class="mb-8">
    <p class="text-lg"><strong>Bio:</strong> Computer Science Engineer specialized in data analysis. Currently working at Zamorano University, passionate about programming, and always open to learning new technologies and practices.</p>
  </div>

</div>
  <div class="mb-8">
    <p class="text-lg"><strong>Contact:</strong></p>
    <ul class="list-disc pl-6">
      <li><a href="mailto:Fernando_lagos00@outlook.com" class="text-blue-500 hover:underline"><i class="fas fa-envelope mr-2"></i> Fernando_lagos00@outlook.com</a></li>
      <li><a href="https://github.com/LagosTech2000" target="_blank" class="text-blue-500 hover:underline"><i class="fab fa-github mr-2"></i> LagosTech2000</a></li>
      <li><a href="https://www.linkedin.com/in/fernando-lagos-407348213/" target="_blank" class="text-blue-500 hover:underline"><i class="fab fa-linkedin mr-2"></i> Fernando Lagos</a></li>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<div class="container mx-auto mt-2">
  <h1 class="text-3xl font-bold mb-4">Task Dashboard</h1>

  <!-- Tasks Overview -->
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-4">
    <!-- General dashboard item -->
    <div class="bg-white rounded-lg shadow-md p-4">
  <h2 class="text-xl font-semibold mb-4">Tasks Overview</h2>

  <!-- Total Tasks -->
  <div class="flex items-center mb-2">
    <span class="mr-2">Total Tasks:</span>
    <%= @tasks.count %>
  </div>

  <!-- Completed Tasks -->
  <div class="flex items-center mb-2">
    <span class="mr-2">Completed:</span>
    <%= @tasks.where(status: 'completed').count %>
  </div>

  <!-- Pending Tasks -->
  <div class="flex items-center mb-4">
    <span class="mr-2">Pending:</span>
    <%= @tasks.where(status: 'pending').count %>
  </div>

  <h2 class="text-xl font-semibold mb-2">Task Progress</h2>

  <!-- Progress Bar -->
  <div class="flex items-center mb-2">
  <% if @tasks.length() >0 %>
    <p class="mr-4"><%= (@tasks.where(status: 'completed').count.to_f / @tasks.count.to_f * 100).round %> % Completed</p>
    <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
      <div class="bg-blue-500 h-2.5 rounded-full" style="width: <%= (@tasks.where(status: 'completed').count.to_f / @tasks.count.to_f * 100).round %>%;"></div>
    </div>
<% end%>
  </div>
</div>

    <!-- Pie Chart -->
    <div class="bg-white rounded-lg shadow-md p-4">
      <h2 class="text-xl font-semibold mb-2">Task Status Distribution</h2>
      <canvas id="taskStatusChart" width="400" height="400"></canvas>
    </div>


</div>

<style>
  .progress-bar {
    height: 20px;
    background-color: #4caf50;
    border-radius: 4px;
  }
</style>

<script>
  var ctx = document.getElementById('taskStatusChart').getContext('2d');
  var taskStatusChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: ['Completed', 'Pending'],
      datasets: [{
        label: 'Task Status Distribution',
        data: [<%= @tasks.where(status: 'completed').count %>, <%= @tasks.where(status: 'pending').count %>],
        backgroundColor: [
          'rgb(18,185,129)',
          'rgb(59,129,246)'
        ],
        borderColor: [
          'rgba(75, 192, 192, 1)',
          'rgba(255, 230, 0, 1)'
        ],
        borderWidth: 1
      }]
    },
    options: {
    }
  });
</script>