config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :messages
  devise_for :users

  get 'home/about'
  root "home#index"

  get '*', to: 'errors#not_found', via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'cancel_form' , to: 'application#cancel_form'
  get 'cancel_modal' , to: 'application#cancel_modal'
  
  resources :conversations do    
    member do
      get 'modal'
      get 'search_users'
    end
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  
    def index
      if current_user 
        
        conversation_id = current_user.conversations.first&.id
        
        if conversation_id
          conversations = ConversationUser.where(conversation_id: conversation_id)
          @conversations = conversations.where.not(user_id: current_user.id)
        else
          @conversations = []
        end
        
        
      end

    end

    def create
    end             

end

app/helpers/chat_helper.rb
module ChatHelper
end

app/views/chats/_chats.html.erb
  <div class="w-full md:w-2/3 lg:w-3/4 bg-white flex flex-col">
          <!-- Messages List -->
          <%= turbo_frame_tag "chat_messages" do %>
            <div class="flex-1 p-4 overflow-y-auto">
              <h2 class="text-xl font-bold mb-4">Chat</h2>
              <div id="chat_messages">
                <%= render partial: 'chats/messages', collection: @messages %>
              </div>
            </div>
          <% end %>

app/views/chats/_messages.html.erb
<div class="flex flex-wrap flex-row pl-2 items-center border-b border-gray-200 py-2">
  <div class="flex-shrink max-w-full px-2 w-3/4">

  <p><strong><%= message.user.email %></strong></p>
  <p><%= message.content %></p>
    <small class="text-gray-500">
      <%= time_ago_in_words(message.created_at) %> ago
    </small>
  </div>
  <%= link_to modal_conversation_path(message.conversation.id) , turbo_frame: '_top' ,format: :turbo_stream, data: { turbo_stream: 'modal' } , class: "bg-green-500 rounded-full hover:bg-yellow-400 text-white font-semibold px-2 rounded focus:outline-none" do %>
  <i class="fas fa-eye">
  </i>
  <% end %>
  
</div>

app/views/chats/index.html.erb
<div class="flex flex-col h-screen">
  <div class="bg-sky-500 p-4">
    <div class="flex justify-between items-center">
      <div class="text-white font-semibold text-center w-full">Chat</div>
      <%= link_to cancel_modal_path, data: { turbo_frame: "modal_#{current_user.id}" }, class: "text-white" do %>
        <i class="fas fa-times text-white"></i>
      <% end %>
    </div>
  </div>
  
  <%= turbo_frame_tag "new_conversation_#{current_user.id}", class: "z-51" do %>        
  <% end %>

  <div class="flex flex-grow overflow-hidden">
    <!-- Left Column: Conversations List -->
    <div class="w-full md:w-1/3 lg:w-1/4 bg-gray-100 border-r overflow-y-auto">
      <div class="p-4">
        <h2 class="text-xl font-bold mb-4">Conversations</h2>
        <%= link_to new_conversation_path, data: { turbo_frame: "new_conversation_#{current_user.id}" }, class: "text-white bg-blue-500 hover:bg-blue-600 p-2 rounded-full mb-4 block text-center" do %>
          <i class="fas fa-plus"></i>
        <% end %>
        <%= turbo_frame_tag "conversations_#{current_user.id}" do %>
          <ul>
            <% @conversations.reverse_each do |conversation| %>
              <li class="mb-4">
                <%= link_to conversation_path(conversation), data: { turbo_frame: "modal" }, class: "flex items-center p-2 hover:bg-gray-200 rounded-lg" do %>
                  <% if conversation.user.avatar.attached? %>
                    <%= image_tag conversation.user.avatar, class: "w-12 h-12 rounded-full mr-3" %>
                  <% end %>
                  <div>
                    <p class="text-gray-900 font-semibold"><%= conversation.user.username %></p>
                    <p class="text-gray-600 text-sm"><%= conversation.user.email %></p>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>

    <!-- Right Column: Chat Messages and Form -->
    <div class="w-full md:w-2/3 lg:w-3/4 bg-white flex flex-col">
      <!-- Messages Receiver details -->
      <div class="p-4 border-b bg-gray-50">
        <h2 class="text-xl font-bold mb-4"><%= @receiver_username %></h2>
      </div>
      <!-- Messages List -->
      <div class="flex-1 p-4 overflow-y-auto">
        <%= turbo_frame_tag "chat_messages_#{current_user.id}" do %>
          <div id="chat_messages" class="space-y-4">
            <%= render partial: 'conversations/messages', collection: @messages %>
          </div>
        <% end %>
      </div>
      <!-- Message Form -->
      <div class="p-4 border-t bg-gray-50 sticky bottom-0">
        <%= form_with model: @message, local: false, data: { turbo_frame: "chat_messages_#{current_user.id}" } do |form| %>
          <div class="flex items-center">
            <%= form.text_area :content, class: "flex-1 border rounded p-2 resize-none", rows: 1, placeholder: "Type a message..." %>
            <%= form.submit "Send", class: "ml-2 bg-blue-500 hover:bg-blue-600 text-white p-2 rounded" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>